### ISSUE TITLE
run python train.py --policy rgl in (torch) root@ninebeita:/home/nine_beita/RelationalGraphLearning/crowd_nav# 

### ISSUE THREAD

**Issue by BeitaNine** [ChanganVR/RelationalGraphLearning#18]
Traceback (most recent call last):
  File "train.py", line 256, in <module>
    main(sys_args)
  File "train.py", line 81, in main
    logging.info('Current git head hash code: {}'.format(repo.head.object.hexsha))
  File "/home/nine_beita/anaconda3/envs/torch/lib/python3.6/site-packages/git/refs/symbolic.py", line 193, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/home/nine_beita/anaconda3/envs/torch/lib/python3.6/site-packages/git/objects/base.py", line 64, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/home/nine_beita/anaconda3/envs/torch/lib/python3.6/site-packages/git/db.py", line 37, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
  File "/home/nine_beita/anaconda3/envs/torch/lib/python3.6/site-packages/git/cmd.py", line 1077, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/home/nine_beita/anaconda3/envs/torch/lib/python3.6/site-packages/git/cmd.py", line 1066, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/home/nine_beita/anaconda3/envs/torch/lib/python3.6/site-packages/git/cmd.py", line 1028, in _parse_object_header
    raise ValueError("SHA could not be resolved, git returned: %r" % (header_line.strip()))
ValueError: SHA could not be resolved, git returned: b''

**Comment by ChanganVR** [comment]
Seems like git related issues. While I don't know what exatly happens here, you could simply comment out the lines where git was used in the code to bypass this.
