### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by xch1176411706** [ChanganVR/RelationalGraphLearning#25]
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    main(sys_args)
  File "train.py", line 156, in main
    trainer.optimize_epoch(il_epochs)
  File "/home/xuech23/Code/RelationalGraphLearning/crowd_nav/utils/trainer.py", line 83, in optimize_epoch
    loss.backward()
  File "/home/xuech23/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/home/xuech23/anaconda3/envs/python3.7/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [100, 6, 32]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Hello, what is the reason for this problem? I also tried to change the python version and the gym version, but this problem always exists. I am looking forward to your answer

thank you

**Comment by zafaralikhan9260** [comment]
@xch1176411706 Did you get the solution to this problem? I am facing the same problem. 
Looking forward.
